import type { Project } from "./types";
import type { GitInfo } from "./git";
import { listProjectBugs, listProjectEnvVars, getClaudeKnowledge } from "./queries";

export const GENERATABLE_DOCS = [
  "CLAUDE.md",
  "PROJECT_OVERVIEW.md",
  "ARCHITECTURE.md",
  "SETUP.md",
  "API.md",
  "DATABASE.md",
  "CHANGELOG.md",
] as const;

export type GeneratableDoc = (typeof GENERATABLE_DOCS)[number];

interface GenContext {
  project: Project;
  technologies: { name: string; category: string }[];
  git: GitInfo;
}

function techList(ctx: GenContext, category?: string): string {
  const items = category ? ctx.technologies.filter((t) => t.category === category) : ctx.technologies;
  if (items.length === 0) return "_None detected._";
  return items.map((t) => `- ${t.name}`).join("\n");
}

function envSection(project: Project): string {
  const vars = listProjectEnvVars(project.id);
  if (vars.length === 0) return "_No environment variables detected for this project._";
  const lines = [
    "| Variable | Status |",
    "|---|---|",
    ...vars.map((v) => `| \`${v.name}\` | ${v.status === "configured" ? "✓ configured" : v.status === "missing" ? "✗ missing" : "unknown"} |`),
  ];
  return lines.join("\n") + "\n\n> Values are never stored or displayed here — only whether each variable is set.";
}

function knownLimitationsSection(project: Project): string {
  const knowledge = getClaudeKnowledge(project.id);
  const bugs = listProjectBugs(project.id).filter((b) => b.status === "open" || b.status === "in_progress");
  const parts: string[] = [];
  if (knowledge?.known_limitations) parts.push(knowledge.known_limitations);
  if (bugs.length > 0) {
    parts.push(
      "Open known bugs:\n" + bugs.map((b) => `- [${b.severity}] ${b.title}`).join("\n")
    );
  }
  return parts.length ? parts.join("\n\n") : "_None recorded yet._";
}

export function generateDoc(doc: GeneratableDoc, ctx: GenContext): string {
  const { project, git } = ctx;
  const header = `<!-- Generated by Perch on ${new Date().toISOString().slice(0, 10)}. Edit freely — this file is only regenerated when you explicitly ask for it, and existing content is never silently overwritten. -->\n\n`;

  switch (doc) {
    case "CLAUDE.md": {
      const knowledge = getClaudeKnowledge(project.id);
      return (
        header +
        `# ${project.name} — Notes for Claude\n\n` +
        `## What this project is\n${project.description ?? "_No description recorded yet._"}\n\n` +
        `${project.purpose ? `## Purpose\n${project.purpose}\n\n` : ""}` +
        `## Status\n- Lifecycle: **${project.status}**\n- Health: **${project.health}**\n- Type: ${project.type}\n\n` +
        `## Tech stack\n${techList(ctx)}\n\n` +
        `## Development rules\n${knowledge?.dev_rules ?? "_None recorded yet — add rules in the Claude Knowledge tab._"}\n\n` +
        `## Things Claude must NOT change\n${knowledge?.do_not_change ?? "_None recorded yet._"}\n\n` +
        `## Check before modifying\n${knowledge?.check_before_modifying ?? "_None recorded yet._"}\n\n` +
        `## Known limitations\n${knownLimitationsSection(project)}\n\n` +
        `## Important decisions\n${knowledge?.important_decisions ?? "_None recorded yet._"}\n`
      );
    }
    case "PROJECT_OVERVIEW.md": {
      return (
        header +
        `# ${project.name}\n\n${project.description ?? "_No description yet._"}\n\n` +
        `- **Type:** ${project.type}\n- **Status:** ${project.status}\n- **Priority:** ${project.priority}\n` +
        `- **Version:** ${project.version ?? "unknown"}\n- **Owner:** ${project.owner ?? "unknown"}\n` +
        `- **Local path:** \`${project.local_path ?? "not set"}\`\n` +
        `- **Production URL:** ${project.production_url ?? "none"}\n- **Staging URL:** ${project.staging_url ?? "none"}\n\n` +
        `## Tech stack\n${techList(ctx)}\n`
      );
    }
    case "ARCHITECTURE.md": {
      const services = techList(ctx, "service");
      const integrations = techList(ctx, "integration");
      return (
        header +
        `# Architecture — ${project.name}\n\n` +
        "```\nUser\n  |\nFrontend\n  |\nAPI / Backend\n  |\nDatabase\n```\n\n" +
        `## Database\n${techList(ctx, "database")}\n\n` +
        `## External services / integrations\n${services}\n${integrations}\n\n` +
        `## Hosting\n${techList(ctx, "hosting")}\n\n` +
        `_This diagram is a generic default — edit it to reflect this project's real request flow once you know it in detail._\n`
      );
    }
    case "SETUP.md": {
      return (
        header +
        `# Setup — ${project.name}\n\n` +
        `## Requirements\n${techList(ctx, "runtime")}\n${techList(ctx, "package_manager")}\n\n` +
        `## Environment variables\n${envSection(project)}\n\n` +
        `## Git\n- Remote: ${git.remoteUrl ?? "_no remote configured_"}\n- Current branch: ${git.branch ?? "unknown"}\n`
      );
    }
    case "API.md": {
      const apis = techList(ctx, "api");
      const services = techList(ctx, "service");
      return (
        header +
        `# API & Integrations — ${project.name}\n\n## Detected APIs\n${apis}\n\n## Detected services\n${services}\n\n` +
        `_Fill in actual endpoint documentation as it becomes known — this section is only seeded with what was auto-detected from dependencies._\n`
      );
    }
    case "DATABASE.md": {
      return (
        header +
        `# Database — ${project.name}\n\n## Engine\n${techList(ctx, "database")}\n\n` +
        `_Add table/entity documentation here as the schema stabilizes._\n`
      );
    }
    case "CHANGELOG.md": {
      return (
        header +
        `# Changelog — ${project.name}\n\n_Generated from recorded changelog entries. Use the Changelog tab to add manual entries or import from git history._\n`
      );
    }
    default:
      return header;
  }
}

export function buildGenContext(project: Project, technologies: { name: string; category: string }[], git: GitInfo): GenContext {
  return { project, technologies, git };
}
